first_name = input("გთხოვთ, შეიყვანეთ თქვენი სახელი: ")
last_name = input("გთხოვთ, შეიყვანეთ თქვენი გვარი: ")
age = input("გთხოვთ, შეიყვანეთ თქვენი ასაკი: ")
email = input("გთხოვთ, შეიყვანეთ თქვენი ელ.ფოსტა: ")

print("მომხმარებლის მონაცემები ---")
print("სახელი:", first_name)
print("გვარი:", last_name)
print("ასაკი:", age)
print("ელ.ფოსტა:", email)
