print("zuka")
print("mother ana")
print("father gela")
print("sister khatia")
print("sister mari")
print("grandmother nani and nunu")
print("grandfather zuri")
print("frend saba")
print("frend ana")
print("frend ikuna")
print("frend nikolozi")
print("frend rezi")